In [18]:
import numpy as np
a=np.random.random((5,4))

In [19]:
b=np.random.random((5,4))

In [20]:
print(a)

[[0.18949185 0.05252158 0.5032128  0.57830652]
 [0.93234428 0.16583311 0.02686659 0.57787318]
 [0.29687347 0.40851973 0.97366552 0.73855779]
 [0.85986028 0.39452199 0.4022694  0.16836556]
 [0.08611994 0.52393588 0.8997445  0.21227079]]


In [21]:
print(b)

[[0.25090203 0.19676072 0.83153015 0.90957322]
 [0.50916662 0.20030906 0.49634366 0.31439404]
 [0.37415206 0.26381761 0.99625852 0.03189196]
 [0.1168973  0.42115674 0.84250506 0.88375569]
 [0.39540521 0.86022855 0.41575427 0.38392532]]


In [30]:
ans=np.zeros([5,4])
for i in range(0,5,1):
    for j in range(0,4,1):
        ans[i][j]=a[i][j]+b[i][j]
       

        

In [33]:
print(ans)


[[0.44039388 0.2492823  1.33474295 1.48787975]
 [1.4415109  0.36614217 0.52321025 0.89226722]
 [0.67102553 0.67233734 1.96992403 0.77044975]
 [0.97675757 0.81567873 1.24477446 1.05212126]
 [0.48152514 1.38416443 1.31549877 0.5961961 ]]


In [37]:
print(ans.shape)

(5, 4)
